services:
  rust-build:
    depends_on:
      - mysql
    build:
      dockerfile: rust-build-debian.dockerfile
      #dockerfile: rust-build-alpine.dockerfile
      args:
        - output_name=portrait-booth
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    environment:
      - LEPTOS_OUTPUT_NAME=portrait-booth
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/portraitdb
