services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    volumes:
      - ./db:/mydata
    command: ["start", "--log", "debug", "--user", "${SURREALDB_USERNAME}", "--pass", "${SURREALDB_PASSWORD}", "file:/mydata/mydatabase.db"]
