services:
  # surrealdb:
  #   image: surrealdb/surrealdb:latest
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./db:/mydata
  #   command: ["start", "--log", "debug", "--user", "${SURREALDB_USERNAME}", "--pass", "${SURREALDB_PASSWORD}", "file:/mydata/mydatabase.db"]
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
  rust-build:
    build:
      dockerfile: rust-build.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      #- ./target:/target
      #- ./target/site/pkg/portrait-booth.wasm:/target/site/pkg/portrait-booth_bg.wasm
      #- ./.env:/.env
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/portraitdb
    command: tail -f /dev/null
