services:
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
